package com.yn.reader.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yn.reader.model.dao.SearchHistoryBean;
import com.yn.reader.model.dao.UserInfo;
import com.yn.reader.model.dao.DownloadChapterBean;
import com.yn.reader.model.dao.BookInfoBean;
import com.yn.reader.model.dao.BookShelfBean;
import com.yn.reader.model.dao.BookContentBean;
import com.yn.reader.model.chapter.ChapterListBean;
import com.yn.reader.model.common.Book;

import com.yn.reader.db.SearchHistoryBeanDao;
import com.yn.reader.db.UserInfoDao;
import com.yn.reader.db.DownloadChapterBeanDao;
import com.yn.reader.db.BookInfoBeanDao;
import com.yn.reader.db.BookShelfBeanDao;
import com.yn.reader.db.BookContentBeanDao;
import com.yn.reader.db.ChapterListBeanDao;
import com.yn.reader.db.BookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchHistoryBeanDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig downloadChapterBeanDaoConfig;
    private final DaoConfig bookInfoBeanDaoConfig;
    private final DaoConfig bookShelfBeanDaoConfig;
    private final DaoConfig bookContentBeanDaoConfig;
    private final DaoConfig chapterListBeanDaoConfig;
    private final DaoConfig bookDaoConfig;

    private final SearchHistoryBeanDao searchHistoryBeanDao;
    private final UserInfoDao userInfoDao;
    private final DownloadChapterBeanDao downloadChapterBeanDao;
    private final BookInfoBeanDao bookInfoBeanDao;
    private final BookShelfBeanDao bookShelfBeanDao;
    private final BookContentBeanDao bookContentBeanDao;
    private final ChapterListBeanDao chapterListBeanDao;
    private final BookDao bookDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchHistoryBeanDaoConfig = daoConfigMap.get(SearchHistoryBeanDao.class).clone();
        searchHistoryBeanDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        downloadChapterBeanDaoConfig = daoConfigMap.get(DownloadChapterBeanDao.class).clone();
        downloadChapterBeanDaoConfig.initIdentityScope(type);

        bookInfoBeanDaoConfig = daoConfigMap.get(BookInfoBeanDao.class).clone();
        bookInfoBeanDaoConfig.initIdentityScope(type);

        bookShelfBeanDaoConfig = daoConfigMap.get(BookShelfBeanDao.class).clone();
        bookShelfBeanDaoConfig.initIdentityScope(type);

        bookContentBeanDaoConfig = daoConfigMap.get(BookContentBeanDao.class).clone();
        bookContentBeanDaoConfig.initIdentityScope(type);

        chapterListBeanDaoConfig = daoConfigMap.get(ChapterListBeanDao.class).clone();
        chapterListBeanDaoConfig.initIdentityScope(type);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        searchHistoryBeanDao = new SearchHistoryBeanDao(searchHistoryBeanDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        downloadChapterBeanDao = new DownloadChapterBeanDao(downloadChapterBeanDaoConfig, this);
        bookInfoBeanDao = new BookInfoBeanDao(bookInfoBeanDaoConfig, this);
        bookShelfBeanDao = new BookShelfBeanDao(bookShelfBeanDaoConfig, this);
        bookContentBeanDao = new BookContentBeanDao(bookContentBeanDaoConfig, this);
        chapterListBeanDao = new ChapterListBeanDao(chapterListBeanDaoConfig, this);
        bookDao = new BookDao(bookDaoConfig, this);

        registerDao(SearchHistoryBean.class, searchHistoryBeanDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(DownloadChapterBean.class, downloadChapterBeanDao);
        registerDao(BookInfoBean.class, bookInfoBeanDao);
        registerDao(BookShelfBean.class, bookShelfBeanDao);
        registerDao(BookContentBean.class, bookContentBeanDao);
        registerDao(ChapterListBean.class, chapterListBeanDao);
        registerDao(Book.class, bookDao);
    }
    
    public void clear() {
        searchHistoryBeanDaoConfig.getIdentityScope().clear();
        userInfoDaoConfig.getIdentityScope().clear();
        downloadChapterBeanDaoConfig.getIdentityScope().clear();
        bookInfoBeanDaoConfig.getIdentityScope().clear();
        bookShelfBeanDaoConfig.getIdentityScope().clear();
        bookContentBeanDaoConfig.getIdentityScope().clear();
        chapterListBeanDaoConfig.getIdentityScope().clear();
        bookDaoConfig.getIdentityScope().clear();
    }

    public SearchHistoryBeanDao getSearchHistoryBeanDao() {
        return searchHistoryBeanDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public DownloadChapterBeanDao getDownloadChapterBeanDao() {
        return downloadChapterBeanDao;
    }

    public BookInfoBeanDao getBookInfoBeanDao() {
        return bookInfoBeanDao;
    }

    public BookShelfBeanDao getBookShelfBeanDao() {
        return bookShelfBeanDao;
    }

    public BookContentBeanDao getBookContentBeanDao() {
        return bookContentBeanDao;
    }

    public ChapterListBeanDao getChapterListBeanDao() {
        return chapterListBeanDao;
    }

    public BookDao getBookDao() {
        return bookDao;
    }

}
